name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker compose build
  publish:
     runs-on: ubuntu-latest
     needs:
       - build
     steps:
        - name: login to docker
          run: docker login --username ${{ secrets.USER }} --password ${{ secrets.PASS }}
      
        - name: PUSH the Docker image
          run: docker push stainlesteel/lastfm-backend:latest
     
